# Generated by Django 2.2 on 2019-06-21 07:20

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190620_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, null=True, unique=True),
        ),
    ]
