# Generated by Django 2.2 on 2019-06-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='shop/static/img/no_image.png', unique=True, upload_to='upload/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
